// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHiYDTHqmP7SRqDVOKM0dpJxlhtgxbRW8',
    appId: '1:262377230628:web:f5526e41931bc5a5d9e3b1',
    messagingSenderId: '262377230628',
    projectId: 'alcohol-speed',
    authDomain: 'alcohol-speed.firebaseapp.com',
    storageBucket: 'alcohol-speed.firebasestorage.app',
    measurementId: 'G-NCR6S7M5LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyt-RLv7fAVnZp3cyBNyJxIbfhwPA5sB4',
    appId: '1:262377230628:android:b3119872a52a06f9d9e3b1',
    messagingSenderId: '262377230628',
    projectId: 'alcohol-speed',
    storageBucket: 'alcohol-speed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKoCRE3aea9ea8KPBzC95oMCIYscKcCw',
    appId: '1:262377230628:ios:282bb281944e8cffd9e3b1',
    messagingSenderId: '262377230628',
    projectId: 'alcohol-speed',
    storageBucket: 'alcohol-speed.firebasestorage.app',
    iosBundleId: 'com.example.archohol',
  );
}
